language: perl
perl:
#    - '5.28'
#    - '5.26'
#    - '5.24'
    - '5.22'
      #    - '5.20'
before_install: eval $(curl https://travis-perl.github.io/init) --auto
matrix:
  include:
    - perl: 5.22
      env: COVERAGE=1
